workflows:
  expo_ios:
    name: Expo iOS Build
    environment:
      node: 18
      expo_username: $EXPO_USERNAME
      expo_password: $EXPO_PASSWORD
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm install -g expo-cli
      - name: Expo prebuild
        script: |
          expo prebuild --clean
      - name: Expo build
        script: |
          expo build:ios --non-interactive
    artifacts:
      - $HOME/build/ios/*.ipa
