workflows:
  expo_ios:
    name: Expo iOS Build
    max_build_duration: 60
    environment:
      groups:
        - expo_credentials
        - mobile_env
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          # first do a clean install (with legacy-peer-deps to avoid ERESOLVE)
          npm ci --legacy-peer-deps
          # make the global Expo CLI available
          npm install -g expo-cli sharp-cli

      - name: Expo prebuild
        script: |
          # run prebuild but skip its built-in install step
          expo prebuild --clean --no-install

      - name: Expo build
        script: |
          expo build:ios --non-interactive

    artifacts:
      - $HOME/build/ios/*.ipa


