workflows:
  expo_ios:
    name: Expo iOS Build
    max_build_duration: 60

    environment:
      groups:
        - expo_credentials
        - mobile_env
      node: "18"

    scripts:
      - name: Install dependencies
        # no cd; install right here at root
        script: |
          npm ci --legacy-peer-deps
          npm install -g eas-cli

      - name: Expo prebuild
        script: |
          npx expo prebuild --clean --no-install --non-interactive

      - name: EAS build for iOS
        script: |
          eas build -p ios --profile production --non-interactive

    artifacts:
      - $HOME/build/ios/*.ipa




