workflows:
  expo_ios:
    name: Expo iOS Build
    environment:
      groups:
        - expo_credentials   # <-- must include the group that has EAS_TOKEN
      node: "18"

    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps
          npm install -g eas-cli

      - name: Expo prebuild
        script: |
          npx expo prebuild --clean --no-install

      - name: EAS build for iOS
        script: |
          # EAS_TOKEN is automatically picked up; no login step needed
          eas build -p ios --profile production

    artifacts:
      - $HOME/build/ios/*.ipa






