workflows:
  expo_ios:
    name: Expo iOS Build
    max_build_duration: 60

    environment:
      # bring in your secrets:
      groups:
        - expo_credentials    # contains $EAS_TOKEN
        - expo_project_id     # contains $EXPO_PROJECT_ID
        - mobile_env

      # use the App Store distribution type and your explicit bundle identifier…
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.threesixsixdegreefitechandsciinstitute.one

    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps
          npm install -g eas-cli

      - name: Expo prebuild
        script: |
          # will pick up extra.eas.projectId from app.json
          npx expo prebuild --clean --no-install

      - name: Debug EAS_TOKEN
        script: |
          echo "EAS_TOKEN length: $(echo -n $EAS_TOKEN | wc -c)"

      - name: EAS build for iOS
        script: |
          # Codemagic/EAS will auto-auth with $EAS_TOKEN
          eas build \
            --platform ios \
            --profile production \
            --non-interactive

    artifacts:
      - $HOME/build/ios/*.ipa




