workflows:
  expo_ios:
    name: Expo iOS Build
    max_build_duration: 60
    environment:
      groups:
        - expo_credentials
        - mobile_env
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps
          npm install -g expo-cli
      - name: Expo prebuild
        script: |
          expo prebuild --clean
      - name: Expo build
        script: |
          expo build:ios --non-interactive
    artifacts:
      - $HOME/build/ios/*.ipa

