workflows:
  expo_ios:
    # … your existing config …

    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps
          npm install -g eas-cli

      - name: Expo prebuild
        script: |
          npx expo prebuild --clean --no-install

      - name: Login to EAS
        script: |
          # non-interactive login with username & password
          eas login --username "$EXPO_USERNAME" --password "$EXPO_PASSWORD" --non-interactive

      - name: EAS build for iOS
        script: |
          eas build -p ios --profile production --non-interactive

    artifacts:
      - $HOME/build/ios/*.ipa





