workflows:
  expo_ios:
    name: Expo iOS Build
    max_build_duration: 60

    environment:
      groups:
        - expo_credentials
        - mobile_env
      node: "18"
      # CI=1 is already set by Codemagic, no need to add it manually

    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps
          npm install -g eas-cli

      - name: Expo prebuild
        script: |
          # CI=1 is detected automatically
          npx expo prebuild --clean --no-install

      - name: EAS build for iOS
        script: |
          # no non-interactive flag needed
          eas build -p ios --profile production

    artifacts:
      - $HOME/build/ios/*.ipa





