workflows:
  expo_ios:
    name: Expo iOS Build
    max_build_duration: 60
    environment:
      node: 18
      # Import your two groups of secrets
      groups:
        - expo_credentials   # contains EXPO_USERNAME, EXPO_PASSWORD
        - mobile_env         # contains OPENAI_API_KEY, SESSION_SECRET, API_BASE_URL
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Expo prebuild
        script: |
          npx expo prebuild --clean
      - name: Expo build iOS
        script: |
          npx expo build:ios --non-interactive --no-wait
    artifacts:
      - $HOME/build/ios/*.ipa

