workflows:
  expo_ios:
    name: Expo iOS Build
    max_build_duration: 60

    environment:
      groups:
        - expo_credentials
        - mobile_env
      node: "18"

    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps
          npm install -g eas-cli

      - name: Expo prebuild
        script: |
          npx expo prebuild --clean --no-install

      - name: Debug EXPO_TOKEN
        script: |
          echo "EXPO_TOKEN length: $(echo -n $EXPO_TOKEN | wc -c)"

      - name: EAS build for iOS
        script: |
          eas build -p ios --profile production

    artifacts:
      - $HOME/build/ios/*.ipa






