workflows:
  expo_ios:
    name: Expo iOS Build
    max_build_duration: 60

    environment:
      groups:
        - expo_credentials
        - mobile_env
      node: "18"

    scripts:
      - name: Install dependencies
        script: |
          cd native_output
          npm ci --legacy-peer-deps
          npm install -g expo-cli eas-cli

      - name: Expo prebuild
        script: |
          cd native_output
          npx expo prebuild --clean --no-install --non-interactive

      - name: EAS build for iOS
        script: |
          cd native_output
          eas build -p ios --profile production --non-interactive

    artifacts:
      - $HOME/build/ios/*.ipa



